public enum PosStatus {
    LEVEL_ONE_PLAYER = 1,
    LEVEL_TWO_PLAYER = 2,
    LEVEL_THREE_PLAYER = 3,
    EMPTY = 10,
    LEVEL_ONE_RIVAL = 11,
    LEVEL_TWO_RIVAL = 12,
    LEVEL_THREE_RIVAL = 13,
    OCCUPIED_PLAYER = 14,
    OCCUPIED_RIVAL = 15
}